#ifndef INTERFACE_PLUGINS_GLOBAL_H
#define INTERFACE_PLUGINS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INTERFACE_PLUGINS_LIBRARY)
#  define INTERFACE_PLUGINS_EXPORT Q_DECL_EXPORT
#else
#  define INTERFACE_PLUGINS_EXPORT Q_DECL_IMPORT
#endif

#endif // INTERFACE_PLUGINS_GLOBAL_H
